export const ApiEndpoints = {
  Auth: {
    Login: 'auths/signin',
    UpdatePassword: 'auths/updatePassword',
    ForgotPassword: 'auths/forgotPassword',
    ResetPassword: 'auths/resetPassword',
    SignUp: 'auths/signup',
    Logout: 'auths/logout',
  },
  Common: {
    CountryList: 'addresses/country/list',
    StateList: 'addresses/state/list',
    CityList: 'addresses/city/list',
  },

  Addresses: {
    AddAddress: 'addresses',
    GetAddressDetail: 'addresses',
    UpdateAddress: 'addresses',
    DeleteAddress: 'addresses',
    GetAddress: 'addresses',
    ExportAddress: 'addresses/export/data',
    ImportAddress: 'addresses/import/data',
  },
  Packages: {
    AddPackage: 'packages/createSinglePackage',
    GetPackagesDetail: 'packages',
    UpdatePackage: 'packages',
    DeletePackage: 'packages',
    GetPackageDetail: 'packages',
  },
  Shipments: {
    AddShipment: {
      AddAddress: 'addresses',
    },
    DeleteShipment: 'shipments',
    ApproveOrReject: 'profiles/shipmentaccount/approved',
    GetShipments: 'shipments',
    GetBulkShipments: 'excelShipments',
    DeleteBulkShipments: 'excelShipments',
    GetShipmentsPaidStatus: 'shipmentPaymentHistories/check/unpaid/invoice',
    CreateSenderAddress: 'shipments/createSenderAddress',
    UpdateSenderAddress: 'shipments/updateSenderAddress',
    CreateReceiverAddress: 'shipments/createReceiverAddress',
    VerifyAdress: 'addresses/validateAddress',
    AddFedExPackage: 'shipments/createPackages',
    AddPackageForUps: 'shipments/createPackagesForUps',
    SelectService: 'shipments/selectService',
    UpdateQuotes: 'shipments/updateQuote',
    UpdateQuotesForUps: 'shipments/updateQuoteUPS',
    CreateShipment: 'shipments/createShipment',
    CreateUpsShipment: 'shipments/createUPSShipment',
    CancelShipment: 'shipments/cancelShipment',
    DeleteCancelShipment: 'shipments/deleteShipmentApi',
    PaymentShipment: 'shipments/shipmentPayment',
    CopyShipment: 'shipments/copyShipment',
    AddCard: 'userCards',
    GetCard: 'userCards',
    PrintLabel: 'shipments/trackingNumberAndLable',
    PrintMultipleLabel: 'shipments/mergePdfFunction',
    Payment: 'shipments/isPaymentSuccess',
    BulkShipment: '/shipments/import',
  },
  Dashboard: {
    ShipmentDashboardSaving: 'dashboards/shipmentSavingGraph',
    ShipmentDashboarShipmentCount: 'dashboards/shipmentCount',
    MailboxGraph: 'dashboards/mailboxGraph',
    MailboxCount: 'dashboards/MailBoxStatusCountApi',
    Status: 'dashboards/dashboardStatusApi',
    AdminAccountGraph: 'dashboards/adminAccountsGraph',
    SubAdminAccountGraph: 'dashboards/revenue/subAdmin',
  },
  MailboxProfiels: {
    Profiles: 'profiles',
    ApproveReject: 'profiles/approveOrReject',
    Plans: 'plans',
    MarkActiveInactive: 'profiles',
    BuyPlans: 'userPlans/buyPlan',
    Payment: 'userPlans/isPaymentSuccess',
    InboxList: 'assignLabels',
    OpenAndScanReq: 'assignLabels/openAndScanReq',
    OpenAndScanRes: 'assignLabels/openAndScanRes',
    ForwardLabel: 'assignLabels/forwardLabel',
    ForwardMultipleLabel: 'assignLabels/forwardMultipleLabels',
    HoldForPickupOtp: 'assignLabels/holdForPickupOtp',
    HoldForPickupMultipleOtp: 'assignLabels/holdForPickupOtp/MultipleLabels',
    HoldForPickup: 'assignLabels/holdForPickup',
    HoldForPickupVerify: 'assignLabels/holdForPickup',
    NotMyMail: 'assignLabels/notMyMail',
    AddInTrash: 'assignLabels/addInTrash',
    AssignLabels: 'assignLabels',
    CancelLabels: 'assignLabels/cancelLabel',
    MarkAsPickup: 'assignLabels',
    AssignPlanToUser: 'userPlans/addPlansToUser',
    AssignScanCount: 'userPlans/addScans',
    ForwardResponse: 'assignLabels/forwardResponse',
    SelectForwardPlan: 'assignLabels/forwardLabelSelectPlan',
    SelectForwardPlanPayment: 'assignLabels/forwardLabelPayment',
    CheckForwardPayment: 'assignLabels/isPaymentSuccess',
    AddShipmentDate: 'assignLabels/forwardLabelAdminResponse',
    GetMailboxScansCount: 'assignLabels/totalCount',
    ChangeDueDate: 'userPlans',
    SendToArchive: 'assignLabels',
  },

  Users: {
    LoginToSubAdminAcc:"users/get/SubAdminToken",
    GetUserDetail: 'users',
    AddToVip: 'marginAndDiscounts/addUserToVip',
    GetUserScanCount: 'users/userScanCount/List',
    GetShipMentUserDetail: '/users/user/list',
    InviteUser: 'users/invite/member',
    CreateProfile: 'users/profile',
    UpdateProfile: 'profiles',
    UploadDocs: 'profiles',
    AddUser: 'users/addCustomer',
    UserTag: 'users/returnPosition/TagOnly',
    UpgradeAccount: 'profiles/upgradeAccount',
    DeleteUserForAdmin: 'users/deleteUserAPIForAdmin',
    updateTour: 'users/updateTour'
  },
  SubAdmin:{
    AddSubAdmin:'users/add/sub/admin',
    GetSubAdminAccountSetting:''
  },

  Invoices: {
    SubAdminMandatoryInvoiceList:'paymentHistories',
    SubAdminInvoices:'paymentHistories',
    ShipmentInvoices: 'shipmentPaymentHistories',
    ShipmentInvoicesCount: 'shipmentPaymentHistories/check/unpaid/invoice',
    MailboxInvoicesCount: 'PaymentHistories/getUnpaid/Invoice/Count',
    MailboxInvoices: 'paymentHistories',
    downloadShipmentInvoice: 'shipmentPaymentHistories/generatePDF',
    downloadMailboxInvoice: 'paymentHistories/generatePDF',
    PayInvoice: 'assignLabels/forwardLabelPayment',
    PayAdminMailboxInvoice: 'paymentHistories/userInvoicePaymentAPI',
    PayAutomaticPlanInvoice: 'PaymentHistories/userInvoicePaymentAPI',
    payShipmentInvoice: 'shipmentPaymentHistories/userInvoicePaymentAPI',
    paySubAdminInvoice: 'paymentHistories/userInvoicePaymentAPI',
    // PaymentVerification:'assignLabels/isPaymentSuccess',
    PaymentVerificationPlan: 'PaymentHistories/isPaymentSuccess',
    ShipmentPaymentVerification: 'shipmentPaymentHistories/isPaymentSuccess',
    CreateMailboxInvoice: 'paymentHistories/assignInvoiceToUser',
    CreateShipmentInvoice: 'shipmentPaymentHistories/assignInvoiceToUser',
    CancelInvoice: 'shipmentPaymentHistories/delete/invoice',
    CancelSubAdminInvoice:'paymentHistories/delete/invoice',
    CancelSpecialInvoice: 'shipmentPaymentHistories/delete/SpecialInvoice',
    CancelMailboxInvoice: 'paymentHistories/delete/invoice',
    Calculate: 'shipmentPaymentHistories/calculate/InvoicesAmount',
    CreateSpecialInvoice: 'shipmentPaymentHistories/create/SpecialInvoice',
  },

  Carrier: {
    Carriers: 'carriers',
  },
  MarginAndDiscount: {
    MarginAndDiscount: 'marginAndDiscounts',
    VipMarginAndDiscount: 'marginAndDiscounts/updatemargin',
  },

  Faq: {
    GetFaq: 'faqs',
    AddFaq: 'faqs',
    EditFaq: 'faqs',
    DeleteFaq: 'faqs',
  },
  AnalyticsAndReports: {
    Logs: 'logs',
    Locations: 'users/get/long/lat',
    Revenue: 'dashboards/totalRevenueAPI',
  },

  Notifications: {
    GetNotifications: 'notifications',
  },
  DownloadForm: {
    DownloadMailboxForm: 'profiles/downloadPdfForm',
  },
  DeleteUserProfile: {
    DeleteUserProfile: 'profiles/deleteProfile',
  },
};
